version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-server-80
    command: --default-authentication-plugin=mysql_native_password
    #        working_dir: /application
    volumes:
      - .:/application
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=.sweetpwd.
      - MYSQL_DATABASE=my_db
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=.mypwd
    ports:
      - "8082:3306"
  website:
    container_name: php72
    image: tut:php_img
    build:
      context: ./
    volumes:
      - /home/canalli/git/2021/src:/var/www/html/
    environment:
      - DB_URL=jdbc:mysql://db_usedr:.mypwd@127.0.0.1:8082/my_db
    ports:
      - 8000:80
    depends_on:
      - mysql
